### PR TITLE
missed bh templates

### PR DESCRIPTION
**Pull request by JiLiZART**
I found some missed bh templates

### CODE REVIEW

**Comment by awinogradov** [comment]
@JiLiZART thanks! Can you check other BH templates? We have #168 and want to support BH but now BH template is old.

**Comment by JiLiZART** [comment]
@awinogradov ok, i'll check it soon.

**Comment by awinogradov** [comment]
@JiLiZART ping ;)

**Comment by JiLiZART** [comment]
@awinogradov pong :). Sorry i have been very busy last week, i check this today

**Comment by JiLiZART** [comment]
@awinogradov i double checked all templates, most of the code is the same. I found little mistakes in couple of templates, thats all.

**Comment by awinogradov** [comment]
@JiLiZART Cool!:) I'll merge it!

**Pull request merged**
